**Part 1**

In [26]:

# By: Baltazar,Cuison,Domingo
# Class Code: 4-326 (6:00 - 8:30P)

# Note: made in Google colab

#1
import numpy as np

In [27]:
#2
print(np.__version__)

1.26.4


In [28]:
#3
print(np.zeros([5]))

[0. 0. 0. 0. 0.]


In [29]:
#4
a = np.array([0,0,0,0,0,0,0,1,0,0,0,0,0,0,0])
print(a)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]


In [36]:
#5
np.random.randint(0,12, size = (4,4))

array([[ 2,  5,  9,  2],
       [ 4,  6,  8,  8],
       [ 6,  0,  3,  7],
       [ 7,  8, 10,  5]])

In [37]:
#6
c = np.array([1,2,4,0,4,0])
c[[0,1,2,4]]

array([1, 2, 4, 4])

In [38]:
#7
np.random.randint(0,20, size = (4,4,4))

array([[[ 7,  5, 12,  9],
        [ 0, 19,  3, 18],
        [19, 13,  8, 18],
        [18, 14, 18,  3]],

       [[11, 11,  9,  7],
        [10, 10, 11, 19],
        [14,  5, 15,  4],
        [12,  0, 14,  5]],

       [[18,  7, 19, 17],
        [11,  7, 14, 17],
        [ 5, 10, 18,  7],
        [ 2, 16, 15,  6]],

       [[16, 18,  9,  6],
        [ 7,  7,  8, 13],
        [ 8, 10,  0,  4],
        [18, 13, 14, 14]]])

In [ ]:
#8
stats = np.random.randint(0,20, size = (15,15))

print(np.min(stats))
print(np.max(stats))

In [ ]:
#9
stats = np.random.randint(0,10, size = (25))
sum = np.sum(stats)
print(stats)
print(np.sum(stats))
print(sum/25)

In [ ]:
#10
a = np.array([[2,4,9]])
b = np.array([[1,14,6]])
print(f"Array 1 = {a}")
print(f"Array 2 = {b}")

In [ ]:
#10.1
[[ 3 18 15 ]]

In [ ]:
#10.2
[[ 1 -10  3 ]]

In [ ]:
#10.3
[[ 2 56 54 ]]

In [ ]:
#10.4
[[ 2.0 0.28571429 1.5 ]]

**Part 2A**

In [ ]:
#1
import numpy as np
a = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a)


[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
#1A
a[1,1]

In [ ]:
#2A
a[1,:]

array([40, 50, 60])

In [ ]:
#3A
a[:,2]

[ 3  7 11]


In [ ]:
#4A
a[1:3, 1:3]

[[ 6  7]
 [10 11]]


**Part 2B**

In [ ]:
#1B
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#2B
print(a[1:3, 1:3])

[[ 6  7]
 [10 11]]


In [ ]:
#3B
print(a[0,::2])

array([1, 3])

In [ ]:
#4B
a = np.array([[9,10,11,12],[5,6,7,8],[1,2,3,4]])
print(a)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [ ]:
#5B
print(a[0:4, 2:4])

[[ 3  4]
 [ 7  8]
 [11 12]]


**Part 2C**

In [ ]:
#1C
import numpy as np
a = np.array([[11,7,33]])
b = np.array([[44,5,18]])
print(f"arr1 = {a}")
print(f"arr2 = {b}")

In [ ]:
#2C
a = np.array([[11,7,33]])
b = np.array([[44,5,18]])

arr = np.concatenate((a,b), axis = 1)
print(arr)

In [ ]:
#3C
a = np.array([[11,7,33]])
b = np.array([[44,5,18]])

np.vstack([a,b])

In [ ]:
#4C
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(f"arr1 = {a}")
print(f"arr2 = {b}")

In [ ]:
#5C
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

np.hstack((a,b))

In [ ]:
#6C
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

np.vstack((a,b))

**Part 3**

In [ ]:
#Task 1
import numpy as np
#1
a = np.array([x for x in range(10,29,2)])
print(a)
print("")

#2
stats = np.random.randint(1,50, size = (4,4))
print(stats)
print("")

#3
np.ones((2,3,4))

[10 12 14 16 18 20 22 24 26 28]

[[22  3 21 38]
 [34 47 46 40]
 [42 49 30 33]
 [36 30 35 41]]



array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
#Task 2
import numpy as np
#1
b = a.reshape(2, 5)
print(b)
print(" ")

#2
print(stats[0:4, 2:4])
print(" ")

#3
stats[stats % 2 == 0] = -1
print(stats)

[[10 12 14 16 18]
 [20 22 24 26 28]]
 
[[21 38]
 [46 40]
 [30 33]
 [35 41]]
 
[[-1  3 21 -1]
 [-1 47 -1 -1]
 [-1 49 -1 33]
 [-1 -1 35 41]]


In [ ]:
#Task 3
import numpy as np
#1
statsmen = np.mean(stats)
print(statsmen)

statsdian = np.median(stats)
print(statsdian)

statsdard = np.std(stats)
print(statsdard)
print(" ")

#2
statsum = np.sum(stats, axis=1)
print(statsum)
print(" ")


#3
maxstats = np.max(stats)
print(maxstats)

statdex = np.unravel_index(np.argmax(stats), stats.shape)
print(statdex)


13.75
-1.0
19.427750770482927
 
[22 44 80 74]
 
49
(2, 1)


In [ ]:
#Task 4
import numpy as np
#1
a = np.random.rand(10,10)
print(a)
print(" ")

#2
b = np.min(a, axis=0)
print(b)
print(" ")

#3
c = np.argsort(a, axis=None)
d = c[-5:]
e = d // a.shape[1]
f = d % a.shape[1]

g = list(zip(e[::-1], f[::-1]))

print(g)


[[0.42575223 0.17715271 0.97114108 0.18009346 0.87055504 0.79096353
  0.8882629  0.56641595 0.00975615 0.22625523]
 [0.16748736 0.4879724  0.00564044 0.92861315 0.52767422 0.29748324
  0.83715801 0.1808532  0.01469423 0.73228813]
 [0.64772484 0.67023235 0.10744313 0.57876498 0.16145589 0.81630205
  0.87912566 0.930106   0.45610575 0.84146916]
 [0.75453036 0.1475701  0.18293304 0.99875542 0.64717632 0.97979128
  0.54791752 0.27998095 0.67241003 0.37661544]
 [0.15494219 0.1375598  0.5064247  0.91180237 0.94438253 0.62484179
  0.63201616 0.35214362 0.59470697 0.29877148]
 [0.86909966 0.907486   0.94440376 0.68551544 0.37687785 0.5311311
  0.69035169 0.20000205 0.1088543  0.31547319]
 [0.34603777 0.30093319 0.56584889 0.23333475 0.02817121 0.82092671
  0.36641881 0.073501   0.64587758 0.43243975]
 [0.50993683 0.32742613 0.25827423 0.31632323 0.55566902 0.19354602
  0.71849424 0.10417461 0.78441319 0.71504494]
 [0.06711277 0.30981768 0.90811751 0.47803443 0.34627821 0.70623519
  0.62413192 